// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: historical_imports.sql

package sqlcgen

import (
	"context"
)

const completeHistoricalImport = `-- name: CompleteHistoricalImport :execrows
UPDATE historical_imports
SET status = 'completed',
    total_records = $2,
    completed_at = NOW(),
    error_message = NULL
WHERE id = $1
  AND status = 'processing'
`

type CompleteHistoricalImportParams struct {
	ID           int64
	TotalRecords int64
}

func (q *Queries) CompleteHistoricalImport(ctx context.Context, arg CompleteHistoricalImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeHistoricalImport, arg.ID, arg.TotalRecords)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHistoricalImport = `-- name: CreateHistoricalImport :one
INSERT INTO historical_imports (reference_year, file_name, file_sha256, status)
VALUES ($1, $2, $3, 'processing')
RETURNING id
`

type CreateHistoricalImportParams struct {
	ReferenceYear int16
	FileName      string
	FileSha256    string
}

func (q *Queries) CreateHistoricalImport(ctx context.Context, arg CreateHistoricalImportParams) (int64, error) {
	row := q.db.QueryRow(ctx, createHistoricalImport, arg.ReferenceYear, arg.FileName, arg.FileSha256)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteHistoricalQuotesByImportID = `-- name: DeleteHistoricalQuotesByImportID :exec
DELETE FROM historical_quotes
WHERE import_id = $1
`

func (q *Queries) DeleteHistoricalQuotesByImportID(ctx context.Context, importID int64) error {
	_, err := q.db.Exec(ctx, deleteHistoricalQuotesByImportID, importID)
	return err
}

const failHistoricalImport = `-- name: FailHistoricalImport :exec
UPDATE historical_imports
SET status = 'failed',
    error_message = $2,
    completed_at = NOW()
WHERE id = $1
`

type FailHistoricalImportParams struct {
	ID           int64
	ErrorMessage *string
}

func (q *Queries) FailHistoricalImport(ctx context.Context, arg FailHistoricalImportParams) error {
	_, err := q.db.Exec(ctx, failHistoricalImport, arg.ID, arg.ErrorMessage)
	return err
}

const getHistoricalImportForUpdate = `-- name: GetHistoricalImportForUpdate :one
SELECT id, status, total_records
FROM historical_imports
WHERE file_sha256 = $1
FOR UPDATE
`

type GetHistoricalImportForUpdateRow struct {
	ID           int64
	Status       string
	TotalRecords int64
}

func (q *Queries) GetHistoricalImportForUpdate(ctx context.Context, fileSha256 string) (GetHistoricalImportForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getHistoricalImportForUpdate, fileSha256)
	var i GetHistoricalImportForUpdateRow
	err := row.Scan(&i.ID, &i.Status, &i.TotalRecords)
	return i, err
}

const restartHistoricalImport = `-- name: RestartHistoricalImport :exec
UPDATE historical_imports
SET status = 'processing',
    total_records = 0,
    error_message = NULL,
    started_at = NOW(),
    completed_at = NULL
WHERE id = $1
`

func (q *Queries) RestartHistoricalImport(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restartHistoricalImport, id)
	return err
}
