// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HistoricalImport struct {
	ID            int64
	ReferenceYear int16
	FileName      string
	FileSha256    string
	Status        string
	TotalRecords  int64
	ErrorMessage  *string
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type HistoricalQuote struct {
	ID                 int64
	ImportID           int64
	LineNumber         int32
	TradingDate        pgtype.Date
	BdiCode            string
	Ticker             string
	MarketType         int16
	ShortName          string
	Specification      string
	Term               *string
	Currency           string
	OpenPrice          pgtype.Numeric
	HighPrice          pgtype.Numeric
	LowPrice           pgtype.Numeric
	AveragePrice       pgtype.Numeric
	ClosePrice         pgtype.Numeric
	BestBidPrice       pgtype.Numeric
	BestAskPrice       pgtype.Numeric
	TradeCount         int32
	TradedQuantity     int64
	TradedVolume       pgtype.Numeric
	StrikePrice        pgtype.Numeric
	OptionIndicator    *string
	ExpirationDate     pgtype.Date
	QuoteFactor        int32
	StrikePoints       pgtype.Numeric
	Isin               string
	DistributionNumber int32
	CreatedAt          pgtype.Timestamptz
}
